# BRUtils document generator jazzy settings

copyright: Copyright 2017 Rien van der Lugt
author: Rien van der Lugt
module: BRUtils
hide_documentation_coverage: true
xcodebuild_arguments: [-target, BRUtils]
github_url: https://github.com/Balancingrock/BRUtils
output: ~/Documents/Websites/sf/projects/brutils/reference
clean: true
theme: fullwidth
