import XCTest
@testable import BRUtils

class BRUtilsTests: XCTestCase {

    #if os(OSX)
    
    static var allTests : [(String, (BRUtilsTests) -> () throws -> Void)] {
        return [
            ("testClampedInt_Int8", testClampedInt_Int8),
            ("testClampedInt8_Int8", testClampedInt8_Int8),
            ("testClampedInt16_Int8", testClampedInt16_Int8),
            ("testClampedInt32_Int8", testClampedInt32_Int8),
            ("testClampedInt64_Int8", testClampedInt64_Int8),
            ("testClampedUInt_Int8", testClampedUInt_Int8),
            ("testClampedUInt8_Int8", testClampedUInt8_Int8),
            ("testClampedUInt16_Int8", testClampedUInt16_Int8),
            ("testClampedUInt32_Int8", testClampedUInt32_Int8),
            ("testClampedUInt64_Int8", testClampedUInt64_Int8),
            ("testClampedFloat_Int8", testClampedFloat_Int8),
            ("testClampedDouble_Int8", testClampedDouble_Int8),
            ("testClampedFloat80_Int8", testClampedFloat80_Int8),
            ("testClampedNSNumber_Int8", testClampedNSNumber_Int8),
            
            ("testClampedInt_UInt8", testClampedInt_UInt8),
            ("testClampedInt8_UInt8", testClampedInt8_UInt8),
            ("testClampedInt16_UInt8", testClampedInt16_UInt8),
            ("testClampedInt32_UInt8", testClampedInt32_UInt8),
            ("testClampedInt64_UInt8", testClampedInt64_UInt8),
            ("testClampedUInt_UInt8", testClampedUInt_UInt8),
            ("testClampedUInt8_UInt8", testClampedUInt8_UInt8),
            ("testClampedUInt16_UInt8", testClampedUInt16_UInt8),
            ("testClampedUInt32_UInt8", testClampedUInt32_UInt8),
            ("testClampedUInt64_UInt8", testClampedUInt64_UInt8),
            ("testClampedFloat_UInt8", testClampedFloat_UInt8),
            ("testClampedDouble_UInt8", testClampedDouble_UInt8),
            ("testClampedFloat80_UInt8", testClampedFloat80_UInt8),
            ("testClampedNSNumber_UInt8", testClampedNSNumber_UInt8),

            ("testClampedInt_Int16", testClampedInt_Int16),
            ("testClampedInt8_Int16", testClampedInt8_Int16),
            ("testClampedInt16_Int16", testClampedInt16_Int16),
            ("testClampedInt32_Int16", testClampedInt32_Int16),
            ("testClampedInt64_Int16", testClampedInt64_Int16),
            ("testClampedUInt_Int16", testClampedUInt_Int16),
            ("testClampedUInt8_Int16", testClampedUInt8_Int16),
            ("testClampedUInt16_Int16", testClampedUInt16_Int16),
            ("testClampedUInt32_Int16", testClampedUInt32_Int16),
            ("testClampedUInt64_Int16", testClampedUInt64_Int16),
            ("testClampedFloat_Int16", testClampedFloat_Int16),
            ("testClampedDouble_Int16", testClampedDouble_Int16),
            ("testClampedFloat80_Int16", testClampedFloat80_Int16),
            ("testClampedNSNumber_Int16", testClampedNSNumber_Int16),
            
            ("testClampedInt_UInt16", testClampedInt_UInt16),
            ("testClampedInt8_UInt16", testClampedInt8_UInt16),
            ("testClampedInt16_UInt16", testClampedInt16_UInt16),
            ("testClampedInt32_UInt16", testClampedInt32_UInt16),
            ("testClampedInt64_UInt16", testClampedInt64_UInt16),
            ("testClampedUInt_UInt16", testClampedUInt_UInt16),
            ("testClampedUInt8_UInt16", testClampedUInt8_UInt16),
            ("testClampedUInt16_UInt16", testClampedUInt16_UInt16),
            ("testClampedUInt32_UInt16", testClampedUInt32_UInt16),
            ("testClampedUInt64_UInt16", testClampedUInt64_UInt16),
            ("testClampedFloat_UInt16", testClampedFloat_UInt16),
            ("testClampedDouble_UInt16", testClampedDouble_UInt16),
            ("testClampedFloat80_UInt16", testClampedFloat80_UInt16),
            ("testClampedNSNumber_UInt16", testClampedNSNumber_UInt16),

            ("testClampedInt_Int32", testClampedInt_Int32),
            ("testClampedInt8_Int32", testClampedInt8_Int32),
            ("testClampedInt16_Int32", testClampedInt16_Int32),
            ("testClampedInt32_Int32", testClampedInt32_Int32),
            ("testClampedInt64_Int32", testClampedInt64_Int32),
            ("testClampedUInt_Int32", testClampedUInt_Int32),
            ("testClampedUInt8_Int32", testClampedUInt8_Int32),
            ("testClampedUInt16_Int32", testClampedUInt16_Int32),
            ("testClampedUInt32_Int32", testClampedUInt32_Int32),
            ("testClampedUInt64_Int32", testClampedUInt64_Int32),
            ("testClampedFloat_Int32", testClampedFloat_Int32),
            ("testClampedDouble_Int32", testClampedDouble_Int32),
            ("testClampedFloat80_Int32", testClampedFloat80_Int32),
            ("testClampedNSNumber_Int32", testClampedNSNumber_Int32),
            
            ("testClampedInt_UInt32", testClampedInt_UInt32),
            ("testClampedInt8_UInt32", testClampedInt8_UInt32),
            ("testClampedInt16_UInt32", testClampedInt16_UInt32),
            ("testClampedInt32_UInt32", testClampedInt32_UInt32),
            ("testClampedInt64_UInt32", testClampedInt64_UInt32),
            ("testClampedUInt_UInt32", testClampedUInt_UInt32),
            ("testClampedUInt8_UInt32", testClampedUInt8_UInt32),
            ("testClampedUInt16_UInt32", testClampedUInt16_UInt32),
            ("testClampedUInt32_UInt32", testClampedUInt32_UInt32),
            ("testClampedUInt64_UInt32", testClampedUInt64_UInt32),
            ("testClampedFloat_UInt32", testClampedFloat_UInt32),
            ("testClampedDouble_UInt32", testClampedDouble_UInt32),
            ("testClampedFloat80_UInt32", testClampedFloat80_UInt32),
            ("testClampedNSNumber_UInt32", testClampedNSNumber_UInt32),

            ("testClampedInt_Int64", testClampedInt_Int64),
            ("testClampedInt8_Int64", testClampedInt8_Int64),
            ("testClampedInt16_Int64", testClampedInt16_Int64),
            ("testClampedInt32_Int64", testClampedInt32_Int64),
            ("testClampedInt64_Int64", testClampedInt64_Int64),
            ("testClampedUInt_Int64", testClampedUInt_Int64),
            ("testClampedUInt8_Int64", testClampedUInt8_Int64),
            ("testClampedUInt16_Int64", testClampedUInt16_Int64),
            ("testClampedUInt32_Int64", testClampedUInt32_Int64),
            ("testClampedUInt64_Int64", testClampedUInt64_Int64),
            ("testClampedFloat_Int64", testClampedFloat_Int64),
            ("testClampedDouble_Int64", testClampedDouble_Int64),
            ("testClampedFloat80_Int64", testClampedFloat80_Int64),
            ("testClampedNSNumber_Int64", testClampedNSNumber_Int64),
            
            ("testClampedInt_UInt64", testClampedInt_UInt64),
            ("testClampedInt8_UInt64", testClampedInt8_UInt64),
            ("testClampedInt16_UInt64", testClampedInt16_UInt64),
            ("testClampedInt32_UInt64", testClampedInt32_UInt64),
            ("testClampedInt64_UInt64", testClampedInt64_UInt64),
            ("testClampedUInt_UInt64", testClampedUInt_UInt64),
            ("testClampedUInt8_UInt64", testClampedUInt8_UInt64),
            ("testClampedUInt16_UInt64", testClampedUInt16_UInt64),
            ("testClampedUInt32_UInt64", testClampedUInt32_UInt64),
            ("testClampedUInt64_UInt64", testClampedUInt64_UInt64),
            ("testClampedFloat_UInt64", testClampedFloat_UInt64),
            ("testClampedDouble_UInt64", testClampedDouble_UInt64),
            ("testClampedFloat80_UInt64", testClampedFloat80_UInt64),
            ("testClampedNSNumber_UInt64", testClampedNSNumber_UInt64),

            ("testClampedInt_Int", testClampedInt_Int),
            ("testClampedInt8_Int", testClampedInt8_Int),
            ("testClampedInt16_Int", testClampedInt16_Int),
            ("testClampedInt32_Int", testClampedInt32_Int),
            ("testClampedInt64_Int", testClampedInt64_Int),
            ("testClampedUInt_Int", testClampedUInt_Int),
            ("testClampedUInt8_Int", testClampedUInt8_Int),
            ("testClampedUInt16_Int", testClampedUInt16_Int),
            ("testClampedUInt32_Int", testClampedUInt32_Int),
            ("testClampedUInt64_Int", testClampedUInt64_Int),
            ("testClampedFloat_Int", testClampedFloat_Int),
            ("testClampedDouble_Int", testClampedDouble_Int),
            ("testClampedFloat80_Int", testClampedFloat80_Int),
            ("testClampedNSNumber_Int", testClampedNSNumber_Int),
            
            ("testClampedInt_UInt", testClampedInt_UInt),
            ("testClampedInt8_UInt", testClampedInt8_UInt),
            ("testClampedInt16_UInt", testClampedInt16_UInt),
            ("testClampedInt32_UInt", testClampedInt32_UInt),
            ("testClampedInt64_UInt", testClampedInt64_UInt),
            ("testClampedUInt_UInt", testClampedUInt_UInt),
            ("testClampedUInt8_UInt", testClampedUInt8_UInt),
            ("testClampedUInt16_UInt", testClampedUInt16_UInt),
            ("testClampedUInt32_UInt", testClampedUInt32_UInt),
            ("testClampedUInt64_UInt", testClampedUInt64_UInt),
            ("testClampedFloat_UInt", testClampedFloat_UInt),
            ("testClampedDouble_UInt", testClampedDouble_UInt),
            ("testClampedFloat80_UInt", testClampedFloat80_UInt),
            ("testClampedNSNumber_UInt", testClampedNSNumber_UInt),
            
            ("testClampedDouble_Float", testClampedDouble_Float),
            ("testClampedFloat80_Float", testClampedFloat80_Float),
            ("testClampedNSNumber_Float", testClampedNSNumber_Float),
        ]
    }
    
    #else
    
    static var allTests : [(String, (BRUtilsTests) -> () throws -> Void)] {
        return [
            ("testClampedInt", testClampedInt_Int8),
            ("testClampedInt8", testClampedInt8_Int8),
            ("testClampedInt16", testClampedInt16_Int8),
            ("testClampedInt32", testClampedInt32_Int8),
            ("testClampedInt64", testClampedInt64_Int8),
            ("testClampedUInt", testClampedUInt_Int8),
            ("testClampedUInt8", testClampedUInt8_Int8),
            ("testClampedUInt16", testClampedUInt16_Int8),
            ("testClampedUInt32", testClampedUInt32_Int8),
            ("testClampedUInt64", testClampedUInt64_Int8),
            ("testClampedFloat", testClampedFloat_Int8),
            ("testClampedDouble", testClampedDouble_Int8),
            ("testClampedFloat80", testClampedFloat80_Int8),
    
            ("testClampedInt_UInt8", testClampedInt_UInt8),
            ("testClampedInt8_UInt8", testClampedInt8_UInt8),
            ("testClampedInt16_UInt8", testClampedInt16_UInt8),
            ("testClampedInt32_UInt8", testClampedInt32_UInt8),
            ("testClampedInt64_UInt8", testClampedInt64_UInt8),
            ("testClampedUInt_UInt8", testClampedUInt_UInt8),
            ("testClampedUInt8_UInt8", testClampedUInt8_UInt8),
            ("testClampedUInt16_UInt8", testClampedUInt16_UInt8),
            ("testClampedUInt32_UInt8", testClampedUInt32_UInt8),
            ("testClampedUInt64_UInt8", testClampedUInt64_UInt8),
            ("testClampedFloat_UInt8", testClampedFloat_UInt8),
            ("testClampedDouble_UInt8", testClampedDouble_UInt8),
            ("testClampedFloat80_UInt8", testClampedFloat80_UInt8),

            ("testClampedInt_Int16", testClampedInt_Int16),
            ("testClampedInt8_Int16", testClampedInt8_Int16),
            ("testClampedInt16_Int16", testClampedInt16_Int16),
            ("testClampedInt32_Int16", testClampedInt32_Int16),
            ("testClampedInt64_Int16", testClampedInt64_Int16),
            ("testClampedUInt_Int16", testClampedUInt_Int16),
            ("testClampedUInt8_Int16", testClampedUInt8_Int16),
            ("testClampedUInt16_Int16", testClampedUInt16_Int16),
            ("testClampedUInt32_Int16", testClampedUInt32_Int16),
            ("testClampedUInt64_Int16", testClampedUInt64_Int16),
            ("testClampedFloat_Int16", testClampedFloat_Int16),
            ("testClampedDouble_Int16", testClampedDouble_Int16),
            ("testClampedFloat80_Int16", testClampedFloat80_Int16),
    
            ("testClampedInt_UInt16", testClampedInt_UInt16),
            ("testClampedInt8_UInt16", testClampedInt8_UInt16),
            ("testClampedInt16_UInt16", testClampedInt16_UInt16),
            ("testClampedInt32_UInt16", testClampedInt32_UInt16),
            ("testClampedInt64_UInt16", testClampedInt64_UInt16),
            ("testClampedUInt_UInt16", testClampedUInt_UInt16),
            ("testClampedUInt8_UInt16", testClampedUInt8_UInt16),
            ("testClampedUInt16_UInt16", testClampedUInt16_UInt16),
            ("testClampedUInt32_UInt16", testClampedUInt32_UInt16),
            ("testClampedUInt64_UInt16", testClampedUInt64_UInt16),
            ("testClampedFloat_UInt16", testClampedFloat_UInt16),
            ("testClampedDouble_UInt16", testClampedDouble_UInt16),
            ("testClampedFloat80_UInt16", testClampedFloat80_UInt16),

            ("testClampedInt_Int32", testClampedInt_Int32),
            ("testClampedInt8_Int32", testClampedInt8_Int32),
            ("testClampedInt16_Int32", testClampedInt16_Int32),
            ("testClampedInt32_Int32", testClampedInt32_Int32),
            ("testClampedInt64_Int32", testClampedInt64_Int32),
            ("testClampedUInt_Int32", testClampedUInt_Int32),
            ("testClampedUInt8_Int32", testClampedUInt8_Int32),
            ("testClampedUInt16_Int32", testClampedUInt16_Int32),
            ("testClampedUInt32_Int32", testClampedUInt32_Int32),
            ("testClampedUInt64_Int32", testClampedUInt64_Int32),
            ("testClampedFloat_Int32", testClampedFloat_Int32),
            ("testClampedDouble_Int32", testClampedDouble_Int32),
            ("testClampedFloat80_Int32", testClampedFloat80_Int32),
    
            ("testClampedInt_UInt32", testClampedInt_UInt32),
            ("testClampedInt8_UInt32", testClampedInt8_UInt32),
            ("testClampedInt16_UInt32", testClampedInt16_UInt32),
            ("testClampedInt32_UInt32", testClampedInt32_UInt32),
            ("testClampedInt64_UInt32", testClampedInt64_UInt32),
            ("testClampedUInt_UInt32", testClampedUInt_UInt32),
            ("testClampedUInt8_UInt32", testClampedUInt8_UInt32),
            ("testClampedUInt16_UInt32", testClampedUInt16_UInt32),
            ("testClampedUInt32_UInt32", testClampedUInt32_UInt32),
            ("testClampedUInt64_UInt32", testClampedUInt64_UInt32),
            ("testClampedFloat_UInt32", testClampedFloat_UInt32),
            ("testClampedDouble_UInt32", testClampedDouble_UInt32),
            ("testClampedFloat80_UInt32", testClampedFloat80_UInt32),
    
            ("testClampedInt_Int64", testClampedInt_Int64),
            ("testClampedInt8_Int64", testClampedInt8_Int64),
            ("testClampedInt16_Int64", testClampedInt16_Int64),
            ("testClampedInt32_Int64", testClampedInt32_Int64),
            ("testClampedInt64_Int64", testClampedInt64_Int64),
            ("testClampedUInt_Int64", testClampedUInt_Int64),
            ("testClampedUInt8_Int64", testClampedUInt8_Int64),
            ("testClampedUInt16_Int64", testClampedUInt16_Int64),
            ("testClampedUInt32_Int64", testClampedUInt32_Int64),
            ("testClampedUInt64_Int64", testClampedUInt64_Int64),
            ("testClampedFloat_Int64", testClampedFloat_Int64),
            ("testClampedDouble_Int64", testClampedDouble_Int64),
            ("testClampedFloat80_Int64", testClampedFloat80_Int64),
    
            ("testClampedInt_UInt64", testClampedInt_UInt64),
            ("testClampedInt8_UInt64", testClampedInt8_UInt64),
            ("testClampedInt16_UInt64", testClampedInt16_UInt64),
            ("testClampedInt32_UInt64", testClampedInt32_UInt64),
            ("testClampedInt64_UInt64", testClampedInt64_UInt64),
            ("testClampedUInt_UInt64", testClampedUInt_UInt64),
            ("testClampedUInt8_UInt64", testClampedUInt8_UInt64),
            ("testClampedUInt16_UInt64", testClampedUInt16_UInt64),
            ("testClampedUInt32_UInt64", testClampedUInt32_UInt64),
            ("testClampedUInt64_UInt64", testClampedUInt64_UInt64),
            ("testClampedFloat_UInt64", testClampedFloat_UInt64),
            ("testClampedDouble_UInt64", testClampedDouble_UInt64),
            ("testClampedFloat80_UInt64", testClampedFloat80_UInt64),

            ("testClampedInt_Int", testClampedInt_Int),
            ("testClampedInt8_Int", testClampedInt8_Int),
            ("testClampedInt16_Int", testClampedInt16_Int),
            ("testClampedInt32_Int", testClampedInt32_Int),
            ("testClampedInt64_Int", testClampedInt64_Int),
            ("testClampedUInt_Int", testClampedUInt_Int),
            ("testClampedUInt8_Int", testClampedUInt8_Int),
            ("testClampedUInt16_Int", testClampedUInt16_Int),
            ("testClampedUInt32_Int", testClampedUInt32_Int),
            ("testClampedUInt64_Int", testClampedUInt64_Int),
            ("testClampedFloat_Int", testClampedFloat_Int),
            ("testClampedDouble_Int", testClampedDouble_Int),
            ("testClampedFloat80_Int", testClampedFloat80_Int),
    
            ("testClampedInt_UInt", testClampedInt_UInt),
            ("testClampedInt8_UInt", testClampedInt8_UInt),
            ("testClampedInt16_UInt", testClampedInt16_UInt),
            ("testClampedInt32_UInt", testClampedInt32_UInt),
            ("testClampedInt64_UInt", testClampedInt64_UInt),
            ("testClampedUInt_UInt", testClampedUInt_UInt),
            ("testClampedUInt8_UInt", testClampedUInt8_UInt),
            ("testClampedUInt16_UInt", testClampedUInt16_UInt),
            ("testClampedUInt32_UInt", testClampedUInt32_UInt),
            ("testClampedUInt64_UInt", testClampedUInt64_UInt),
            ("testClampedFloat_UInt", testClampedFloat_UInt),
            ("testClampedDouble_UInt", testClampedDouble_UInt),
            ("testClampedFloat80_UInt", testClampedFloat80_UInt),

            ("testClampedDouble_Float", testClampedDouble_Float),
            ("testClampedFloat80_Float", testClampedFloat80_Float),
            ("testClampedNSNumber_Float", testClampedNSNumber_Float),
        ]
    }

    #endif
}
